# Generated by Django 5.1.1 on 2024-09-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_b', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybook',
            options={'ordering': ['author', 'title']},
        ),
        migrations.RemoveField(
            model_name='librarybook',
            name='id',
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
